[toolchain]
anchor_version = "1.1.2"

[features]
resolution = false
skip-lint = false

[programs.devnet]
climate_market = "8THvFM9mEZEyzcxgnYU18BS4GNDJqK1Xixkjnuc5yted"

[programs.localnet]
climate_market = "EkcwkAzNUCGRcKCA5WJc7GCtUXooubkm3ktesBWQXPBt"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx vitest run --config programs/climate_market/vitest.config.mts"

[hooks]
